server:
  port: 16666

spring:
  profiles:
    active: local

  datasource:
    url: ${breeze.mysql.url}
    username: ${breeze.mysql.username}
    password: ${breeze.mysql.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource

  # redis配置
  redis:
    host: ${breeze.redis.host}
    port: ${breeze.redis.port}
    timeout: 60s
    #password: ${breeze.redis.password}
    lettuce:
      pool:
        max-active: 10
        max-wait: -1ms
        max-idle: 10
        min-idle: 2
  jackson:
    time-zone: Asia/Shanghai
    date-format: yyyy-MM-dd HH:mm:ss

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.rmny.tech.breeze.bean.entity
  configuration:
    map-underscore-to-camel-case: true

# 分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
#
logging:
  config: classpath:config/${breeze.log.config-name}